-- 0008_person_day_digest
-- One person, one KST day, everything they did.
--
-- Generated by a batch and never by hand. The row is the record of what the
-- timeline said on the day it was built, so a digest read next month is the
-- same digest somebody read then, rather than a fresh query that quietly
-- changed because a backfill landed in between.
--
-- `events` holds every activity, in time order, not a selection. HK, 2026-09-11:
-- "주요가 아니라 모든 것" -- all of it, mechanically, with no summarising and
-- no model in the path. A digest that silently drops the long tail is a
-- digest nobody can use to answer "what did this actually consist of", which
-- is the only question it exists for.
--
-- The day is KST. Every window in this system is KST because that is the day
-- the people being described actually worked.

CREATE TABLE IF NOT EXISTS person_day_digest (
    person_id text NOT NULL REFERENCES org_person(person_id),
    day date NOT NULL,
    generated_at timestamptz NOT NULL DEFAULT now(),
    -- The generator's version, so a digest built by older logic is
    -- identifiable and re-buildable without guessing which ones are stale.
    generator text NOT NULL,
    events_total integer NOT NULL DEFAULT 0,
    -- Per source and per event type, from the same rows `events` holds, so
    -- the headline numbers and the list can never disagree.
    counts jsonb NOT NULL DEFAULT '{}'::jsonb,
    events jsonb NOT NULL DEFAULT '[]'::jsonb,
    -- Set when the day held more events than one row should carry. Never
    -- silent: a truncated digest says so, with how many it left out.
    truncated_at integer,
    PRIMARY KEY (person_id, day)
);

CREATE INDEX IF NOT EXISTS person_day_digest_day_idx
    ON person_day_digest (day DESC, person_id);
CREATE INDEX IF NOT EXISTS person_day_digest_generated_idx
    ON person_day_digest (generated_at DESC);

COMMENT ON TABLE person_day_digest IS
    'One row per person per KST day, built by the digest batch from '
    'timeline_events. Holds every activity in time order, not a selection.';
COMMENT ON COLUMN person_day_digest.events IS
    'Every activity that day, ordered by occurred_at. Mechanically derived '
    'from timeline_events -- no summarisation, no model.';
